<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\doubl\Documents\Gitprojects\CirkusLuna\CirkusLuna.ClassLibrary\Service\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\doubl\Documents\Gitprojects\CirkusLuna\CirkusLuna.ClassLibrary\Service\.editorconfig" />
  </ItemGroup>

</Project>
